package com.elvarg.game.world;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Reads and writes the generated world record.
 *
 * Mirrors the shape of Elvarg's existing {@code PlayerPersistence}: an interface
 * over a directory of JSON, easy to inspect by hand and easy to swap for
 * something else later. The world file holds identities and spawns; terrain is
 * in the map files and is not duplicated here.
 *
 * @author EverGielinor
 */
public final class WorldPersistence {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    private final Path worldFile;

    public WorldPersistence(Path dataDirectory) {
        this.worldFile = dataDirectory.resolve("world.json");
    }

    public boolean exists() {
        return Files.exists(worldFile);
    }

    public Path file() {
        return worldFile;
    }

    public GeneratedWorld load() throws IOException {
        try (Reader reader = Files.newBufferedReader(worldFile)) {
            GeneratedWorld world = GSON.fromJson(reader, GeneratedWorld.class);
            if (world == null) {
                throw new IOException("world file is empty: " + worldFile);
            }
            if (world.generatorVersion != GeneratedWorld.GENERATOR_VERSION) {
                // Loud rather than silent: a world made by a different generator is
                // still playable, but its seed no longer means what it used to.
                System.out.println("[world] NOTE: " + worldFile.getFileName()
                        + " was generated by version " + world.generatorVersion
                        + ", this build is version " + GeneratedWorld.GENERATOR_VERSION
                        + ". Loading it as-is; re-roll to regenerate with this version.");
            }
            return world;
        }
    }

    public void save(GeneratedWorld world) throws IOException {
        Files.createDirectories(worldFile.toAbsolutePath().getParent());
        // Write beside the target and move into place, so an interrupted save never
        // leaves a half-written world that fails to parse on the next boot.
        Path temporary = worldFile.resolveSibling("world.json.tmp");
        try (Writer writer = Files.newBufferedWriter(temporary)) {
            GSON.toJson(world, writer);
        }
        Files.move(temporary, worldFile,
                java.nio.file.StandardCopyOption.REPLACE_EXISTING,
                java.nio.file.StandardCopyOption.ATOMIC_MOVE);
    }
}
